In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spotify-recommendation/yes.py
/kaggle/input/spotify-recommendation/good.json
/kaggle/input/spotify-recommendation/dislike.json
/kaggle/input/spotify-recommendation/no.py
/kaggle/input/spotify-recommendation/data.csv


In [2]:
df = pd.read_csv('/kaggle/input/spotify-recommendation/data.csv')
df

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0           0.803  0.6240    7    -6.764     0       0.0477        0.4510   
1           0.762  0.7030   10    -7.951     0       0.3060        0.2060   
2           0.261  0.0149    1   -27.528     1       0.0419        0.9920   
3           0.722  0.7360    3    -6.994     0       0.0585        0.4310   
4           0.787  0.5720    1    -7.516     1       0.2220        0.1450   
..            ...     ...  ...       ...   ...          ...           ...   
190         0.166  0.0551    9   -19.494     0       0.0520        0.9760   
191         0.862  0.6240    3   -11.630     1       0.0565        0.0192   
192         0.499  0.3510    9   -11.509     0       0.0448        0.9510   
193         0.574  0.7290   10    -5.838     0       0.0965        0.0406   
194         0.747  0.6660   11    -7.845     1       0.1970        0.1300   

     instrumentalness  liveness  valence    tempo  duration_ms  \
0            0.000734    0.1000   0.6280   95.968       304524   
1            0.000000    0.0912   0.5190  151.329       247178   
2            0.897000    0.1020   0.0382   75.296       286987   
3            0.000001    0.1230   0.5820   89.860       208920   
4            0.000000    0.0753   0.6470  155.117       179413   
..                ...       ...      ...      ...          ...   
190          0.635000    0.1190   0.1430  176.616       206520   
191          0.000153    0.0465   0.8820  124.896       254240   
192          0.000099    0.1180   0.6160   90.664       235947   
193          0.000004    0.1940   0.4130  110.547       190239   
194          0.000000    0.3600   0.5310   77.507       177213   

     time_signature  liked  
0                 4      0  
1                 4      1  
2                 4      0  
3                 4      1  
4                 4      1  
..              ...    ...  
190               3      0  
191               4      0  
192               4      0  
193               5      1  
194               4      1  

[195 rows x 14 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   danceability      195 non-null    float64
 1   energy            195 non-null    float64
 2   key               195 non-null    int64  
 3   loudness          195 non-null    float64
 4   mode              195 non-null    int64  
 5   speechiness       195 non-null    float64
 6   acousticness      195 non-null    float64
 7   instrumentalness  195 non-null    float64
 8   liveness          195 non-null    float64
 9   valence           195 non-null    float64
 10  tempo             195 non-null    float64
 11  duration_ms       195 non-null    int64  
 12  time_signature    195 non-null    int64  
 13  liked             195 non-null    int64  
dtypes: float64(9), int64(5)
memory usage: 21.5 KB


**As you see, there is no missing data but this file have not the song IDs; For content based recommendation or any other recommendation system we need to know IDs or name of the songs for recommending them to the user**

**So, I am going to read json files and convert them to pandas dataframes**

In [4]:
import json

with open('../input/spotify-recommendation/good.json', 'r') as f:
    data = json.load(f)

good_df = pd.DataFrame(data['audio_features'])
good_df

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0          0.749   0.839    6    -4.847     1       0.2970        0.0867   
1          0.573   0.581   10    -9.026     0       0.3390        0.7530   
2          0.800   0.719    7    -6.262     1       0.2340        0.1090   
3          0.778   0.632    8    -6.415     1       0.1250        0.0404   
4          0.797   0.852    8    -5.202     1       0.2410        0.0555   
..           ...     ...  ...       ...   ...          ...           ...   
95         0.616   0.534   10   -10.264     0       0.4830        0.6390   
96         0.802   0.549    5    -8.600     0       0.0631        0.2680   
97         0.767   0.659    7    -4.541     1       0.0387        0.7850   
98         0.752   0.468    0    -9.966     1       0.3330        0.8050   
99         0.797   0.654    8    -7.373     1       0.2450        0.6330   

    instrumentalness  liveness  valence    tempo            type  \
0           0.000000    0.2040    0.804  172.068  audio_features   
1           0.000001    0.1300    0.351   76.506  audio_features   
2           0.000000    0.0580    0.815  143.975  audio_features   
3           0.000000    0.0912    0.827  140.951  audio_features   
4           0.000024    0.0536    0.480  136.035  audio_features   
..               ...       ...      ...      ...             ...   
95          0.000000    0.0844    0.556  170.054  audio_features   
96          0.004960    0.0984    0.498  138.984  audio_features   
97          0.000000    0.1120    0.631   90.056  audio_features   
98          0.000000    0.1360    0.716   82.795  audio_features   
99          0.000000    0.1060    0.640  145.121  audio_features   

                        id                                   uri  \
0   55mcupbf7cIsuCEVAuTJVk  spotify:track:55mcupbf7cIsuCEVAuTJVk   
1   57RtLWT7IpugV0yi5bsxJk  spotify:track:57RtLWT7IpugV0yi5bsxJk   
2   5VyfAfp2Yt3qaeuvq55ll3  spotify:track:5VyfAfp2Yt3qaeuvq55ll3   
3   3eWHY75nDgte70hh5yf4UW  spotify:track:3eWHY75nDgte70hh5yf4UW   
4   2UwrB6Ge6mPfUV8yGvAfX7  spotify:track:2UwrB6Ge6mPfUV8yGvAfX7   
..                     ...                                   ...   
95  3dl4lXWlOxnGo94OqNtpdq  spotify:track:3dl4lXWlOxnGo94OqNtpdq   
96  3DWDcsDoXRIFynCREIkibM  spotify:track:3DWDcsDoXRIFynCREIkibM   
97  6fmtZEUoGwxPNvUgr0NJm1  spotify:track:6fmtZEUoGwxPNvUgr0NJm1   
98  2edc1m7WXxdBA61WlxSInp  spotify:track:2edc1m7WXxdBA61WlxSInp   
99  3qjDXaWCalJ9ZzaHBG4j3V  spotify:track:3qjDXaWCalJ9ZzaHBG4j3V   

                                           track_href  \
0   https://api.spotify.com/v1/tracks/55mcupbf7cIs...   
1   https://api.spotify.com/v1/tracks/57RtLWT7Ipug...   
2   https://api.spotify.com/v1/tracks/5VyfAfp2Yt3q...   
3   https://api.spotify.com/v1/tracks/3eWHY75nDgte...   
4   https://api.spotify.com/v1/tracks/2UwrB6Ge6mPf...   
..                                                ...   
95  https://api.spotify.com/v1/tracks/3dl4lXWlOxnG...   
96  https://api.spotify.com/v1/tracks/3DWDcsDoXRIF...   
97  https://api.spotify.com/v1/tracks/6fmtZEUoGwxP...   
98  https://api.spotify.com/v1/tracks/2edc1m7WXxdB...   
99  https://api.spotify.com/v1/tracks/3qjDXaWCalJ9...   

                                         analysis_url  duration_ms  \
0   https://api.spotify.com/v1/audio-analysis/55mc...       111000   
1   https://api.spotify.com/v1/audio-analysis/57Rt...       169347   
2   https://api.spotify.com/v1/audio-analysis/5Vyf...       230854   
3   https://api.spotify.com/v1/audio-analysis/3eWH...       224029   
4   https://api.spotify.com/v1/audio-analysis/2Uwr...       102353   
..                                                ...          ...   
95  https://api.spotify.com/v1/audio-analysis/3dl4...       146480   
96  https://api.spotify.com/v1/audio-analysis/3DWD...       184627   
97  https://api.spotify.com/v1/audio-analysis/6fmt...       186720   
98  https://api.spotify.com/v1/audio-analysis/2edc...       179253   
99

**There is some unnecessary information in the data such URI, URL and duration of song that I think it's better to drop them!**

**On the other hand, we add a column called like to indicate whether the song is good or bad (Of course, according to the opinion of the data producer!)**

In [5]:
good_df = good_df.drop(columns=['type','uri','track_href','analysis_url','duration_ms'])
good_df['like'] = 1
good_df

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0          0.749   0.839    6    -4.847     1       0.2970        0.0867   
1          0.573   0.581   10    -9.026     0       0.3390        0.7530   
2          0.800   0.719    7    -6.262     1       0.2340        0.1090   
3          0.778   0.632    8    -6.415     1       0.1250        0.0404   
4          0.797   0.852    8    -5.202     1       0.2410        0.0555   
..           ...     ...  ...       ...   ...          ...           ...   
95         0.616   0.534   10   -10.264     0       0.4830        0.6390   
96         0.802   0.549    5    -8.600     0       0.0631        0.2680   
97         0.767   0.659    7    -4.541     1       0.0387        0.7850   
98         0.752   0.468    0    -9.966     1       0.3330        0.8050   
99         0.797   0.654    8    -7.373     1       0.2450        0.6330   

    instrumentalness  liveness  valence    tempo                      id  \
0           0.000000    0.2040    0.804  172.068  55mcupbf7cIsuCEVAuTJVk   
1           0.000001    0.1300    0.351   76.506  57RtLWT7IpugV0yi5bsxJk   
2           0.000000    0.0580    0.815  143.975  5VyfAfp2Yt3qaeuvq55ll3   
3           0.000000    0.0912    0.827  140.951  3eWHY75nDgte70hh5yf4UW   
4           0.000024    0.0536    0.480  136.035  2UwrB6Ge6mPfUV8yGvAfX7   
..               ...       ...      ...      ...                     ...   
95          0.000000    0.0844    0.556  170.054  3dl4lXWlOxnGo94OqNtpdq   
96          0.004960    0.0984    0.498  138.984  3DWDcsDoXRIFynCREIkibM   
97          0.000000    0.1120    0.631   90.056  6fmtZEUoGwxPNvUgr0NJm1   
98          0.000000    0.1360    0.716   82.795  2edc1m7WXxdBA61WlxSInp   
99          0.000000    0.1060    0.640  145.121  3qjDXaWCalJ9ZzaHBG4j3V   

    time_signature  like  
0                4     1  
1                4     1  
2                4     1  
3                4     1  
4                4     1  
..             ...   ...  
95               4     1  
96               4     1  
97               4     1  
98               4     1  
99               4     1  

[100 rows x 14 columns]

In [6]:
with open('../input/spotify-recommendation/dislike.json', 'r') as f:
    data = json.load(f)

bad_df = pd.DataFrame(data['audio_features'])
bad_df

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0          0.357   0.980    6    -6.835     1       0.0790      0.000052   
1          0.446   0.977   10    -5.036     0       0.0781      0.000535   
2          0.291   0.980    1    -5.138     1       0.1530      0.001270   
3          0.462   0.974    1    -5.820     1       0.0816      0.000029   
4          0.338   0.988    8    -7.290     0       0.0865      0.000083   
..           ...     ...  ...       ...   ...          ...           ...   
90         0.798   0.746   10    -8.639     1       0.0313      0.030400   
91         0.651   0.811   10   -13.870     1       0.0318      0.064800   
92         0.705   0.847    6    -2.588     1       0.0361      0.414000   
93         0.819   0.811    6    -7.760     0       0.0349      0.203000   
94         0.656   0.900    5    -9.583     0       0.0354      0.079100   

    instrumentalness  liveness  valence    tempo            type  \
0           0.843000    0.0768    0.368   96.969  audio_features   
1           0.472000    0.1050    0.339  172.059  audio_features   
2           0.091000    0.1020    0.257   79.792  audio_features   
3           0.723000    0.0751    0.399  107.877  audio_features   
4           0.833000    0.0377    0.449   99.046  audio_features   
..               ...       ...      ...      ...             ...   
90          0.361000    0.0703    0.965  128.553  audio_features   
91          0.029300    0.1000    0.962  112.126  audio_features   
92          0.000003    0.4060    0.743  120.527  audio_features   
93          0.005580    0.1390    0.766  106.684  audio_features   
94          0.001420    0.3540    0.947  108.698  audio_features   

                        id                                   uri  \
0   4pFC6tuWErxbO61oFFq3BQ  spotify:track:4pFC6tuWErxbO61oFFq3BQ   
1   6V3SNkvi4BnfmZU0j7s9TQ  spotify:track:6V3SNkvi4BnfmZU0j7s9TQ   
2   1Ds58cpyJzL0YTKk02vh1C  spotify:track:1Ds58cpyJzL0YTKk02vh1C   
3   77QKNMGwlnzxsTZPYfByMu  spotify:track:77QKNMGwlnzxsTZPYfByMu   
4   3bQoMbPYOvvseHaSOWAQ3Q  spotify:track:3bQoMbPYOvvseHaSOWAQ3Q   
..                     ...                                   ...   
90  1QqsAlhs7pxcXs9BMB1Nv5  spotify:track:1QqsAlhs7pxcXs9BMB1Nv5   
91  6VuIKS2Z27jCutIapgCUZF  spotify:track:6VuIKS2Z27jCutIapgCUZF   
92  7sMGwiS4vOMcz86ZY3vKYM  spotify:track:7sMGwiS4vOMcz86ZY3vKYM   
93  4JsQkSOE4taeyhH3pv1een  spotify:track:4JsQkSOE4taeyhH3pv1een   
94  3P2zU7fEjnZRunH124QnJL  spotify:track:3P2zU7fEjnZRunH124QnJL   

                                           track_href  \
0   https://api.spotify.com/v1/tracks/4pFC6tuWErxb...   
1   https://api.spotify.com/v1/tracks/6V3SNkvi4Bnf...   
2   https://api.spotify.com/v1/tracks/1Ds58cpyJzL0...   
3   https://api.spotify.com/v1/tracks/77QKNMGwlnzx...   
4   https://api.spotify.com/v1/tracks/3bQoMbPYOvvs...   
..                                                ...   
90  https://api.spotify.com/v1/tracks/1QqsAlhs7pxc...   
91  https://api.spotify.com/v1/tracks/6VuIKS2Z27jC...   
92  https://api.spotify.com/v1/tracks/7sMGwiS4vOMc...   
93  https://api.spotify.com/v1/tracks/4JsQkSOE4tae...   
94  https://api.spotify.com/v1/tracks/3P2zU7fEjnZR...   

                                         analysis_url  duration_ms  \
0   https://api.spotify.com/v1/audio-analysis/4pFC...       242760   
1   https://api.spotify.com/v1/audio-analysis/6V3S...       284400   
2   https://api.spotify.com/v1/audio-analysis/1Ds5...       270920   
3   https://api.spotify.com/v1/audio-analysis/77QK...       186576   
4   https://api.spotify.com/v1/audio-analysis/3bQo...       221960   
..                                                ...          ...   
90  https://api.spotify.com/v1/audio-analysis/1Qqs...       655213   
91  https://api.spotify.com/v1/audio-analysis/6VuI...       186573   
92  https://api.spotify.com/v1/audio-analysis/7sMG...       228120   
93  https://api.spotify.com/v1/audio-analysis/4JsQ...       246760   
94

In [7]:
bad_df = bad_df.drop(columns=['type','uri','track_href','analysis_url','duration_ms'])
bad_df['like'] = 0
bad_df

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0          0.357   0.980    6    -6.835     1       0.0790      0.000052   
1          0.446   0.977   10    -5.036     0       0.0781      0.000535   
2          0.291   0.980    1    -5.138     1       0.1530      0.001270   
3          0.462   0.974    1    -5.820     1       0.0816      0.000029   
4          0.338   0.988    8    -7.290     0       0.0865      0.000083   
..           ...     ...  ...       ...   ...          ...           ...   
90         0.798   0.746   10    -8.639     1       0.0313      0.030400   
91         0.651   0.811   10   -13.870     1       0.0318      0.064800   
92         0.705   0.847    6    -2.588     1       0.0361      0.414000   
93         0.819   0.811    6    -7.760     0       0.0349      0.203000   
94         0.656   0.900    5    -9.583     0       0.0354      0.079100   

    instrumentalness  liveness  valence    tempo                      id  \
0           0.843000    0.0768    0.368   96.969  4pFC6tuWErxbO61oFFq3BQ   
1           0.472000    0.1050    0.339  172.059  6V3SNkvi4BnfmZU0j7s9TQ   
2           0.091000    0.1020    0.257   79.792  1Ds58cpyJzL0YTKk02vh1C   
3           0.723000    0.0751    0.399  107.877  77QKNMGwlnzxsTZPYfByMu   
4           0.833000    0.0377    0.449   99.046  3bQoMbPYOvvseHaSOWAQ3Q   
..               ...       ...      ...      ...                     ...   
90          0.361000    0.0703    0.965  128.553  1QqsAlhs7pxcXs9BMB1Nv5   
91          0.029300    0.1000    0.962  112.126  6VuIKS2Z27jCutIapgCUZF   
92          0.000003    0.4060    0.743  120.527  7sMGwiS4vOMcz86ZY3vKYM   
93          0.005580    0.1390    0.766  106.684  4JsQkSOE4taeyhH3pv1een   
94          0.001420    0.3540    0.947  108.698  3P2zU7fEjnZRunH124QnJL   

    time_signature  like  
0                4     0  
1                4     0  
2                4     0  
3                3     0  
4                4     0  
..             ...   ...  
90               4     0  
91               4     0  
92               4     0  
93               4     0  
94               4     0  

[95 rows x 14 columns]

**And now we can merge two dataframes to one**

In [8]:
df = good_df.merge(bad_df, how='outer')
df

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0           0.749   0.839    6    -4.847     1       0.2970        0.0867   
1           0.573   0.581   10    -9.026     0       0.3390        0.7530   
2           0.800   0.719    7    -6.262     1       0.2340        0.1090   
3           0.778   0.632    8    -6.415     1       0.1250        0.0404   
4           0.797   0.852    8    -5.202     1       0.2410        0.0555   
..            ...     ...  ...       ...   ...          ...           ...   
190         0.798   0.746   10    -8.639     1       0.0313        0.0304   
191         0.651   0.811   10   -13.870     1       0.0318        0.0648   
192         0.705   0.847    6    -2.588     1       0.0361        0.4140   
193         0.819   0.811    6    -7.760     0       0.0349        0.2030   
194         0.656   0.900    5    -9.583     0       0.0354        0.0791   

     instrumentalness  liveness  valence    tempo                      id  \
0            0.000000    0.2040    0.804  172.068  55mcupbf7cIsuCEVAuTJVk   
1            0.000001    0.1300    0.351   76.506  57RtLWT7IpugV0yi5bsxJk   
2            0.000000    0.0580    0.815  143.975  5VyfAfp2Yt3qaeuvq55ll3   
3            0.000000    0.0912    0.827  140.951  3eWHY75nDgte70hh5yf4UW   
4            0.000024    0.0536    0.480  136.035  2UwrB6Ge6mPfUV8yGvAfX7   
..                ...       ...      ...      ...                     ...   
190          0.361000    0.0703    0.965  128.553  1QqsAlhs7pxcXs9BMB1Nv5   
191          0.029300    0.1000    0.962  112.126  6VuIKS2Z27jCutIapgCUZF   
192          0.000003    0.4060    0.743  120.527  7sMGwiS4vOMcz86ZY3vKYM   
193          0.005580    0.1390    0.766  106.684  4JsQkSOE4taeyhH3pv1een   
194          0.001420    0.3540    0.947  108.698  3P2zU7fEjnZRunH124QnJL   

     time_signature  like  
0                 4     1  
1                 4     1  
2                 4     1  
3                 4     1  
4                 4     1  
..              ...   ...  
190               4     0  
191               4     0  
192               4     0  
193               4     0  
194               4     0  

[195 rows x 14 columns]

**For content based filtering we're going to use cosine similarity; however for a fairer comparison, we can drop like column and get their similarity only through the characteristics of each song**

In [9]:
temp_df = df.drop(columns=['id', 'like'])
temp_df

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0           0.749   0.839    6    -4.847     1       0.2970        0.0867   
1           0.573   0.581   10    -9.026     0       0.3390        0.7530   
2           0.800   0.719    7    -6.262     1       0.2340        0.1090   
3           0.778   0.632    8    -6.415     1       0.1250        0.0404   
4           0.797   0.852    8    -5.202     1       0.2410        0.0555   
..            ...     ...  ...       ...   ...          ...           ...   
190         0.798   0.746   10    -8.639     1       0.0313        0.0304   
191         0.651   0.811   10   -13.870     1       0.0318        0.0648   
192         0.705   0.847    6    -2.588     1       0.0361        0.4140   
193         0.819   0.811    6    -7.760     0       0.0349        0.2030   
194         0.656   0.900    5    -9.583     0       0.0354        0.0791   

     instrumentalness  liveness  valence    tempo  time_signature  
0            0.000000    0.2040    0.804  172.068               4  
1            0.000001    0.1300    0.351   76.506               4  
2            0.000000    0.0580    0.815  143.975               4  
3            0.000000    0.0912    0.827  140.951               4  
4            0.000024    0.0536    0.480  136.035               4  
..                ...       ...      ...      ...             ...  
190          0.361000    0.0703    0.965  128.553               4  
191          0.029300    0.1000    0.962  112.126               4  
192          0.000003    0.4060    0.743  120.527               4  
193          0.005580    0.1390    0.766  106.684               4  
194          0.001420    0.3540    0.947  108.698               4  

[195 rows x 12 columns]

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

cs = cosine_similarity(temp_df)
print(cs)

[[1.         0.99116164 0.99977722 ... 0.99980266 0.99866096 0.99803467]
 [0.99116164 1.         0.99370509 ... 0.9920779  0.99620468 0.99594091]
 [0.99977722 0.99370509 1.         ... 0.99973161 0.99947031 0.99893282]
 ...
 [0.99980266 0.9920779  0.99973161 ... 1.         0.99862962 0.99774453]
 [0.99866096 0.99620468 0.99947031 ... 0.99862962 1.         0.99982514]
 [0.99803467 0.99594091 0.99893282 ... 0.99774453 0.99982514 1.        ]]


In [11]:
songs_ids = pd.Series(df.index, index=df['id'])
songs_ids

id
55mcupbf7cIsuCEVAuTJVk      0
57RtLWT7IpugV0yi5bsxJk      1
5VyfAfp2Yt3qaeuvq55ll3      2
3eWHY75nDgte70hh5yf4UW      3
2UwrB6Ge6mPfUV8yGvAfX7      4
                         ... 
1QqsAlhs7pxcXs9BMB1Nv5    190
6VuIKS2Z27jCutIapgCUZF    191
7sMGwiS4vOMcz86ZY3vKYM    192
4JsQkSOE4taeyhH3pv1een    193
3P2zU7fEjnZRunH124QnJL    194
Length: 195, dtype: int64

**We need a function that get an ID and return top 10 similar songs using cosine similarity scores**

In [12]:
def song_recommender(song_id, cs=cs):
    #index of the song using its id
    idx = songs_ids[song_id]
    #get cosine similarity scores for that song, sort them and get top 10 similar
    scores = list(enumerate(cs[idx]))
    sorted_scores = sorted(scores, key= lambda x:x[1], reverse=True)[1:11]
    #get the indexes of top 10 similar songs
    rec_songs_idxs = [i[0] for i in sorted_scores]
    print("Is this song good or bad? (good=1 , bad=0)\n", df[df['id']==candid_id]['like'].values[0])
    print("\nTop 10 similar songs:\n")
    return df[['id','like']].iloc[rec_songs_idxs]

**In the end, for testing the model, we pass some IDs to model and get return top 10 similar songs and their popularity status**

In [14]:
candid_id = '55mcupbf7cIsuCEVAuTJVk'
song_recommender(song_id=candid_id)

Is this song good or bad? (good=1 , bad=0)
 1

Top 10 similar songs:



id  like
71  03JjVo4OYciAi88SEdtDii     1
48  6mkAhxAj1y5zvXWefkd9y7     1
89  0PieJw6d3jyki3JTxgZhIr     1
36  35tyQCmxn6cj2r7eAb4JXP     1
88  4QMaRC93F0aFx3S648CLyh     1
92  0i8JFpqe9cKwnrcvoNgl1L     1
21  6mKLhdZIMaHpZ9kbmq9SOS     1
54  205HNJ73cgpC0LAOnuQiWT     1
68  2fl01uGwbppFEci7qij1lU     1
44  4VdQCcXDuzb6Ks1yLT9FnO     1

In [16]:
candid_id = '3P2zU7fEjnZRunH124QnJL'
song_recommender(song_id=candid_id)

Is this song good or bad? (good=1 , bad=0)
 0

Top 10 similar songs:



id  like
175  1qiQduM84A0VeH8Y2uAbqi     0
183  7e176FKv7cq6SG9EXYMLoQ     0
176  3SnGymj6ijE2iuUfWxLo1q     0
135  4LAGHmHcSt0HHwXCJcFri6     0
139  7dn6WQzScfRGpp7XdTiCj0     0
58   4W1RGS4ncIY1yrz38rysN3     1
188  1X4gWy941yRMvafHs4n2sQ     0
193  4JsQkSOE4taeyhH3pv1een     0
67   5T5mtNBCvVQ01WPr3MRzUY     1
14   4zHabeonyLGTgnR9R5RY3X     1